name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.x"

      - name: Running Lint (go vet)
        run: go vet -json ./core

      - name: Running Test
        run: go test ./core -coverprofile=coverage.out
