name: CI

on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.x"

      - name: Running Lint (go vet)
        run: go vet -json ./core

      - name: Running Test
        run: go test ./core -coverprofile=coverage.out
